// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/footer/index.vue')['default']
    Header: typeof import('./src/components/header/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Navbar: typeof import('./src/components/header/components/navbar.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NThemeEditor: typeof import('naive-ui')['NThemeEditor']
    PopVideo: typeof import('./src/components/pop-video/index.vue')['default']
    TapSidesToSeek: typeof import('./src/components/pop-video/TapSidesToSeek.vue')['default']
    Title: typeof import('./src/components/title/index.vue')['default']
    Todo: typeof import('./src/components/todo/index.vue')['default']
  }
}

export { }
