// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/footer/index.vue')['default']
    FooterCpn: typeof import('./src/components/footerCpn/index.vue')['default']
    Header: typeof import('./src/components/header/index.vue')['default']
    HeaderTop: typeof import('./src/components/header/headerTop/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NavbarArea: typeof import('./src/components/header/navbarArea/index.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NIcon: typeof import('naive-ui')['NIcon']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NSpace: typeof import('naive-ui')['NSpace']
    NThemeEditor: typeof import('naive-ui')['NThemeEditor']
    Title: typeof import('./src/components/title/index.vue')['default']
    TitleCpn: typeof import('./src/components/titleCpn/index.vue')['default']
    Todo: typeof import('./src/components/todo/index.vue')['default']
    TodoCpn: typeof import('./src/components/todoCpn/index.vue')['default']
  }
}

export { }
